version: '3'
services:
  front:
    build: . 
    container_name: frontend.-test
    volumes:
      - '.:/app'
      - '/app/node_modules'
    working_dir: /app
    command: bash -c "npm run build && npm run server"

